### ISSUE TITLE
consider adding a licence

### ISSUE THREAD

**Issue by melvincarvalho** [colealbon/git-nostr#2]
consider adding a license so that other projects are allowed reuse and improve code

AIUI this is not permissible unless there's a license in the repo, the code is copyright of the author

normally I add MIT to my work, so perhaps something to consider or clarify

**Comment by colealbon** [comment]
Marching orders via github issues are ignored.

alternatives:

submit an issue via eponymous tool (preferred):
- git nostr issue --secretkey xxxxxx --publickey 0f578badfbc982c36aac5ca8ea973a0bea5ab93adaef9885e163fbe8d7e5e631 --title "feature - add MIT license"  --description "AIUI this is not permissible unless there's a license in the repo, the code is copyright of the author normally I add MIT to my work, so perhaps something to consider or clarify"

or use a more manual approach
- nostril --envelope --sec "$SECRETKEY" --kind 7777 --tag purpose "git-nostr-issue" --tag title "$TITLE" --content "$DESCRIPTION" -p $PUBLICKEY  | $RELAY

**Comment by melvincarvalho** [comment]
> Marching orders via github issues are ignored.

No worries.  Nostr works with both open source and proprietary projects.  Best of luck!
